import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./context/cookiesContext";
import { ThemeModeScript } from "flowbite-react";
import LayoutClient from "@/components/layoutClient";
import { StoreProvider } from "../app/storeProvider";
export const metadata: Metadata = {
  title: "Task managemnet",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body>
        <StoreProvider>
          <AppProvider>
            <LayoutClient>{children}</LayoutClient>
          </AppProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
