import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "./context/cookiesContext";

import LayoutClient from "@/components/layoutClient";
export const metadata: Metadata = {
  title: "Task managemnet",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <AppProvider>
          <LayoutClient>{children}</LayoutClient>
        </AppProvider>
      </body>
    </html>
  );
}
