import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Projects",
  description: "Task management generated by create next app",
};

export default function ProjectLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full flex justify-center pt-10 h-full bg-blue-100">
      <div className="p-3 w-[80%]">{children}</div>
    </section>
  );
}
